# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 40
  - name: CV
    url: 'uploads/CV.pdf'
    weight: 50
  - name: Working Papers
    url: '/research/'
    identifier: "research"
    weight: 60
  - name: Publications
    url: '#publications'
    weight: 70  
  - name: Posts
    url: '#posts'
    weight: 80
  - name: Contact
    url: '#contact'
    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
